#pragma once
// The purpose of this file is to convert includes from the files generated by XamlCompiler into imports.
// For the .g.cpp files generated by the XamlCompiler, this file is added to the beginning of the include list via the `/FI`. For `.xaml.cpp` or `.xaml.h` files, it should be included before `xaml.h` or `xaml.g.h` but after other header files.

// The .cpp files generated by the XamlCompiler currently do not support modules. After defining this macro, all C++/WinRT header files will become empty.
#ifndef WINRT_IMPORT_MODULE
#define WINRT_IMPORT_MODULE
#endif

// The .cpp files generated by the XamlCompiler still include these header files, so they also need to be blocked out.
#ifndef __unknwn_h__
#define __unknwn_h__
#endif
#ifndef __RPC_H__
#define __RPC_H__
#endif
#ifndef __RPCNDR_H__
#define __RPCNDR_H__
#endif
#ifndef _INC_WINAPIFAMILY
#define _INC_WINAPIFAMILY
#endif
#ifndef _INC_WINPACKAGEFAMILY
#define _INC_WINPACKAGEFAMILY
#endif
#ifndef _OLE2_H_
#define _OLE2_H_
#endif
#ifndef _INC_WINDOWS
#define _INC_WINDOWS
#endif
#ifndef _INC_SDKDDKVER
#define _INC_SDKDDKVER
#endif
#ifndef _FUNCTIONAL_
#define _FUNCTIONAL_
#endif
#ifndef _VECTOR_
#define _VECTOR_
#endif
#ifndef _MAP_
#define _MAP_
#endif
#ifndef _MUTEX_
#define _MUTEX_
#endif
#ifndef _REGEX_
#define _REGEX_
#endif
#ifndef _MEMORY_
#define _MEMORY_
#endif
#ifndef _STRING_
#define _STRING_
#endif

// Import these modules to satisfy the requirements of the .cpp files generated by the XamlCompiler.
import std;
import winrt.Windows.Foundation;
import winrt.Microsoft.UI.Xaml.Markup;
import winrt.Microsoft.UI.Xaml.Interop;
import winrt.Windows.UI.Xaml.Interop;
import winrt.Microsoft.UI.Xaml;
import winrt.Microsoft.UI.Xaml.XamlTypeInfo;
